[account]
#unlock=["0x43EC6d0942f7fAeF069F7F63D0384a27f529B062", "0x9e602164C5826ebb5A6B68E4AFD9Cd466043dc4A", "0x5Bd738164C61FB50eb12E227846CbaeF2dE965Aa", "0xC04eE4131895F1d0C294D508AF65D94060AA42BB", "0x07D899C4aC0c1725C35C5f816e60273B33a964F7"]
#password=["./basepassword.file"]

[mining]
extra_data = "Affinity"
# New pending block will be created for all transactions (both local and external).
reseal_on_txs = "all"
# New pending block will be created only once per 4000 milliseconds.
reseal_min_period = 4000
# Parity will keep/relay at most 2048 transactions in queue.
tx_queue_size = 2048
gas_floor_target = "80000000"
gas_cap = "80000000"
tx_gas_limit = "10000000"

[footprint]
# If defined will never use more then 256MB for all caches. (Overrides other cache settings).
cache_size = 256

[misc]
# Logging pattern (`<module>=<level>`, e.g. `own_tx=trace`).
logging = "miner=trace,own_tx=trace"
